### ISSUE TITLE
Add commands to pb-git-hooks to get information about the lints

### ISSUE THREAD

**Issue by tomphp** [PurpleBooth/pb-git-hooks#18]
e.g.

- `pb-git-hooks lint available` to show all available ones
- `pb-git-hooks lint status <lint>` to check if a lint is enabled or disabled
- `pb-git-hooks lint enabled` to list all enabled lints

**Comment by PurpleBooth** [comment]
- [x] Available
- [ ] Status
- [ ] Enabled

**Comment by PurpleBooth** [comment]
This is now implemented
